In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

### 2. 不看讲义代码，重新实现一遍张三李四的考场故事。
假设ddd是期中考试成绩，ddd2是期末考试成绩，请自由创建ddd2，并将其与ddd相加，求期中期末
平均值。
假设张三期中考试数学被发现作弊，要记为0分，如何实现？
李四因为举报张三作弊立功，期中考试所有科目加100分，如何实现？
后来老师发现有一道题出错了，为了安抚学生情绪，给每位学生每个科目都加10分，如何实现？

In [2]:
def create_df(index,columns,shape):
    data = np.round(np.random.uniform(100,size=shape),1)
    return DataFrame(data,index,columns)
ddd = create_df(['张三','李四','王二','赵一'],
               ['语文','数学','英语'],
               (4,3))
ddd2 = create_df(['张三','李四','王二','赵一'],
               ['语文','数学','英语'],
               (4,3))

In [3]:
ddd

语文    数学    英语
张三  64.2  19.5  44.1
李四  72.7  37.3  56.8
王二  70.8  53.2  71.1
赵一  85.1  13.7  14.2

In [4]:
ddd2

语文    数学    英语
张三  16.8  22.6  79.3
李四  92.8  74.1  54.7
王二  15.2  98.9   2.6
赵一  17.6  96.5  42.3

In [5]:
(ddd+ddd2)/2

语文     数学     英语
张三  40.50  21.05  61.70
李四  82.75  55.70  55.75
王二  43.00  76.05  36.85
赵一  51.35  55.10  28.25

In [6]:
ddd.loc['张三','数学'] = 0
ddd

语文    数学    英语
张三  64.2   0.0  44.1
李四  72.7  37.3  56.8
王二  70.8  53.2  71.1
赵一  85.1  13.7  14.2

In [7]:
ddd.loc['李四'] += 100
ddd

语文     数学     英语
张三   64.2    0.0   44.1
李四  172.7  137.3  156.8
王二   70.8   53.2   71.1
赵一   85.1   13.7   14.2

In [8]:
ddd.add(10)

语文     数学     英语
张三   74.2   10.0   54.1
李四  182.7  147.3  166.8
王二   80.8   63.2   81.1
赵一   95.1   23.7   24.2

3. 用今天所学的DataFrame知识点，写一个小说。
参考选题：
- 菜市场张大妈和李大爷的故事
- Python程序员狂虐Java程序员的故事

张大妈和李大爷今天都去菜市场买菜，张大妈买了土豆、白菜、胡萝卜、西红柿，
李大爷买了土豆、黄瓜、西红柿，大妈考虑到家里人多，就又多买了1个白菜回家了，
大爷发现买的土豆有1个坏了就退了1个土豆，又买了1斤猪肉也回去了。大爷，大妈一共买了些什么？

In [17]:
def create_cai(index,columns):
    shape = (len(index), len(columns))
    data = np.random.randint(1,5,size=shape)
    return DataFrame(data,index,columns)
shopping = create_cai(['土豆','白菜','胡萝卜','西红柿','黄瓜'],
                     ['张大妈','李大爷'])
shopping.loc[['黄瓜'],'张大妈'] = 0
shopping.loc[['白菜','胡萝卜'],'李大爷'] = 0
shopping

张大妈  李大爷
土豆     2    3
白菜     4    0
胡萝卜    3    0
西红柿    2    3
黄瓜     0    1

In [18]:
shopping.loc['白菜','张大妈'] += 1
shopping.loc['土豆','李大爷'] -= 1
shopping.loc['猪肉','李大爷'] = 1
shopping.fillna(0)

张大妈  李大爷
土豆   2.0  2.0
白菜   5.0  0.0
胡萝卜  3.0  0.0
西红柿  2.0  3.0
黄瓜   0.0  1.0
猪肉   0.0  1.0

# 补数据分析第一天的作业

#扩展任务 1.给定一个数据库表A，
内容如下： year,month,amount 1991,1, 1.1 1991,2, 1.2 1992,1, 2.1 1992,2, 2,2 请写出SQL语句，
让查询的结果为： year，m1, m2 1991,1.1, 1.2 1992,2.1, 2,2 提示： 使用if()函数或自连表查询

create table A(year char(4), month varchar(2), amount float);
insert into A values
('1991','1', 1.1),
('1991','2', 1.2),
('1992','1', 2.1),
('1992','2', 2.2);
#自连表查询
select a1.year, a1.amount as m1, a2.amount as m2 
from A a1 join A a2 on (a1.year = a2.year) where a1.month='1' and a2.month='2';
#if()函数
select year,max(round(if(month='1',amount,0),1)) as m1,max(round(if(month='2',amount,0),1)) as m2 
from A group by year;

In [19]:
#13、给定一个二维矩阵，如何交换其中两行的元素？
arr13 = np.random.randint(1,10,size=(2,4))
arr13

array([[3, 6, 2, 9],
       [5, 8, 3, 3]])

In [20]:
arr13[[0,1]] = arr13[[1,0]]
arr13

array([[5, 8, 3, 3],
       [3, 6, 2, 9]])

In [23]:
#14、创建一个100000长度的随机数组，使用两种方法对其求三次方，并比较所用时间
np.random.seed(0)
x = np.random.rand(100000)
display(x)
display(x*x*x)
display(np.power(x,3))
%time np.power(x,3)
%time x*x*x

array([0.5488135 , 0.71518937, 0.60276338, ..., 0.81013284, 0.55103228,
       0.22575586])

array([0.16530058, 0.36581638, 0.21899821, ..., 0.53170251, 0.16731355,
       0.01150581])

array([0.16530058, 0.36581638, 0.21899821, ..., 0.53170251, 0.16731355,
       0.01150581])

Wall time: 5 ms
Wall time: 1.01 ms


array([0.16530058, 0.36581638, 0.21899821, ..., 0.53170251, 0.16731355,
       0.01150581])

In [25]:
#15、创建一个5*3随机矩阵和一个3*2随机矩阵，求矩阵积
arr15 = np.random.randint(10,size=(5,3))
arr_15 = np.random.randint(10,size=(3,2))


In [26]:
arr15

array([[5, 8, 1],
       [8, 4, 6],
       [0, 8, 2],
       [0, 5, 0],
       [8, 1, 4]])

In [27]:
arr_15

array([[7, 5],
       [5, 6],
       [2, 6]])

In [29]:
np.dot(arr15,arr_15)

array([[ 77,  79],
       [ 88, 100],
       [ 44,  60],
       [ 25,  30],
       [ 69,  70]])

In [30]:
#16、矩阵的每一行的元素都减去该行的平均值


#17、打印出以下函数（要求使用np.zeros创建8*8的矩阵）：
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

In [32]:
arr17 = np.zeros((8,8),dtype=int)
arr17[1::2,::2] = 1
arr17[::2,1::2] = 1
print(arr17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#18、正则化一个5*5随机矩阵
正则的概念：假设a是矩阵中的一个元素，
max/min分别是矩阵元素的最大最小值，则正则化后a = (a - min)/(max - min)

In [34]:
arr18 = np.random.randint(10,100,size = (5,5))
print(arr18)
arr18max, arr18min = arr18.max(), arr18.min()
arr18 = (arr18 - arr18min)/(arr18max - arr18min)
print('*'*20)
print(arr18)

[[60 20 55 18 21]
 [37 12 86 46 47]
 [15 85 21 16 76]
 [47 83 69 76 62]
 [46 72 80 47 57]]
********************
[[0.64864865 0.10810811 0.58108108 0.08108108 0.12162162]
 [0.33783784 0.         1.         0.45945946 0.47297297]
 [0.04054054 0.98648649 0.12162162 0.05405405 0.86486486]
 [0.47297297 0.95945946 0.77027027 0.86486486 0.67567568]
 [0.45945946 0.81081081 0.91891892 0.47297297 0.60810811]]


In [ ]:
#19、将一个一维数组转化为二进制表示矩阵。例如
[1,2,3]
转化为
[[0,0,1],
[0,1,0],
[0,1,1]]

In [ ]:
#20、实现冒泡排序法