In [2]:
import numpy as np

In [3]:
#1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1
arr1 = np.random.randint(10,size=10)
arr1[4] = 1
arr1

array([8, 8, 9, 4, 1, 2, 4, 5, 7, 6])

In [4]:
#2、创建一个元素为从10到49的ndarray对象
arr2 = np.arange(10,50)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
#3、将第2题的所有元素位置反转
arr3 = arr2[::-1]
arr3

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [8]:
#4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素
arr4 = np.random.random(size=(10,10))
arr4

array([[0.40638869, 0.83115001, 0.76617745, 0.68491632, 0.05205545,
        0.15165888, 0.4590845 , 0.2028923 , 0.20760255, 0.4237689 ],
       [0.37899328, 0.66239251, 0.30078818, 0.48088646, 0.2343385 ,
        0.09097078, 0.15465436, 0.02874143, 0.37146593, 0.90537127],
       [0.11894646, 0.65420839, 0.01363454, 0.21081267, 0.96230202,
        0.71570742, 0.86206446, 0.40509635, 0.7682233 , 0.04363581],
       [0.9290901 , 0.92528869, 0.25497196, 0.03527191, 0.06458056,
        0.99694989, 0.08857395, 0.43685927, 0.922886  , 0.47407263],
       [0.07189091, 0.74267343, 0.2870828 , 0.49680557, 0.67363336,
        0.22249249, 0.91742556, 0.93978097, 0.33980944, 0.62790241],
       [0.33875974, 0.53202479, 0.31335088, 0.60052793, 0.82181954,
        0.79866364, 0.17564019, 0.80734087, 0.46648477, 0.10175502],
       [0.50883154, 0.90555401, 0.27120903, 0.59635193, 0.4845352 ,
        0.21399715, 0.3898717 , 0.04825078, 0.70652485, 0.82656753],
       [0.2355859 , 0.98654691, 0.3130926

In [10]:
arr4.max()

0.9969498873289357

In [24]:
#5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0
arr5 = np.zeros((10,10)).astype(int)
arr5

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [46]:
arr5[[0,9]][:,[0,9]] = 1
arr5

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [36]:
#6、创建一个每一行都是从0到4的5*5矩阵
arr6 = np.arange(5)
arr6 = np.vstack((arr6,arr6,arr6,arr6,arr6))
arr6

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [42]:
#7、创建一个范围在(0,1)之间的长度为12的等差数列
arr7 = np.linspace(0,1,num=12,endpoint= True)
arr7

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [48]:
#8、创建一个长度为10的随机数组并排序
arr8 = np.random.randint(100,size=10)
arr8 = np.sort(arr8)
arr8

array([ 9,  9, 10, 11, 17, 28, 37, 46, 51, 60])

In [137]:
#9、创建一个长度为10的随机数组并将最大值替换为0
arr9 = np.random.randint(1,8,size=10)
for i in range(10):
    if arr9[i] == arr9.max():
        arr9[i] = 0
arr9

array([0, 5, 0, 4, 2, 1, 5, 0, 0, 4])

In [116]:
#10、如何根据第3列来对一个5*5矩阵排序？
arr10 = np.random.randint(100,size=(5,5))
arr10[np.argsort(arr10[:,2])]

array([[35, 71, 15, 97, 28],
       [35, 48, 27,  4, 48],
       [98, 46, 50, 28, 81],
       [38, 98, 72, 99, 80],
       [63, 38, 92, 20, 15]])

In [10]:
#11、给定一个4维矩阵，如何得到最后两维的和？
arr11 = np.random.randint(100,size=(2,3,4,5))
arr11


array([[[[ 3, 43, 64, 33, 84],
         [66, 17, 31, 94, 58],
         [97, 65, 89, 84, 55],
         [97, 16,  4, 88, 37]],

        [[11, 63, 94, 99, 38],
         [36, 74, 37, 45, 47],
         [43, 15, 72, 40, 84],
         [69, 98, 13, 86,  2]],

        [[60, 62, 96, 73, 90],
         [72, 92, 20, 54, 87],
         [28, 43, 31, 81, 71],
         [13, 43, 70, 30, 28]]],


       [[[78, 13, 79, 29, 52],
         [80, 65, 80,  5, 89],
         [10, 24, 20, 60, 49],
         [59, 21, 21, 16, 86]],

        [[35, 13, 50, 46, 76],
         [36, 20, 34, 46, 47],
         [15, 97, 36, 13, 52],
         [50, 34,  6, 67, 56]],

        [[ 4,  6, 10, 26, 23],
         [ 3, 30, 90, 70, 79],
         [49, 68, 41, 47, 92],
         [54, 78, 19, 29, 23]]]])

In [83]:
for i in range(2):
    for j in range(3):
        print(np.sum(arr11[i][j]))

997
1222
1059
1153
769
1052


In [140]:
#12、给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？
arr12 = np.array([1,2,3,4,5])
arr_12 = np.zeros(shape=17,dtype=int)
arr_12[::4] = arr12
arr_12

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

In [3]:
#13、给定一个二维矩阵，如何交换其中两行的元素？
arr13 = np.random.randint(1,10,size=(2,4))
arr13


array([[3, 2, 1, 4],
       [1, 3, 5, 7]])

In [4]:
arr13[[0,1]] = arr13[[1,0]]
arr13

array([[1, 3, 5, 7],
       [3, 2, 1, 4]])