In [2]:
import numpy as np

In [2]:
np.version

<module 'numpy.version' from 'G:\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>

In [3]:
np._version_

AttributeError: module 'numpy' has no attribute '_version_'

In [4]:
np.__version__

'1.16.2'

##创建ndarray对象
-使用list列表和numpy.array()函数
-使用numpy库中提供的相关函数

In [5]:
#使用list方式创建多维数组ndarray对象
arr1 = np.array([1,2,3],dtype=np.int8)
#[注意] 数组的元素类型都是统一的，
#       如果不统一时，则按int>float>str 从低到高的优先级进行转换
arr1

array([1, 2, 3], dtype=int8)

In [7]:
arr2 = np.array(['disen',20,99.5],dtype = np.int8)
arr2

ValueError: invalid literal for int() with base 10: 'disen'

In [8]:
arr2 = np.array(['disen',20,99.5])
arr2

array(['disen', '20', '99.5'], dtype='<U5')

In [10]:
#是否可以通过元组来创建ndarray
for _ in np.array((1,2,3)):
    print(_)

1
2
3


In [11]:
# ndarrray是一个多维数组的对象
#可以是一维的,二维，...n维的
data = (
    (1,2),
    (3,4),
    (5,6),
)
arr3 = np.array(data,np.int8)
arr3

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int8)

### numpy的函数创建ndarray

In [18]:
#1. 创建3*3的二维数组，每个元素都是1
arr_1 = np.ones(shape=(3,3),dtype = np.int8)
arr_1.astype(np.int8)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [19]:
#2. 创建3*3*2的三维数组，每个元素都是0
arr_2 = np.zeros((3,3,2),dtype=np.int)
arr_2

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [21]:
#创建4*3的二维数组，每个元素都是9
arr_3 = np.full((4,3),fill_value=9,dtype=np.int8)
arr_3

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]], dtype=int8)

In [22]:
#4.创建5*5的二维数组，对角线上的每个元素都是1的单位矩阵
arr_4 = np.eye(5,dtype=int)
arr_4

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### 创建等差数列
- numpy.linspace()
- numpy.arrange()

In [24]:
arr_5 = np.linspace(2,100,num=50,endpoint=True).astype(int)
arr_5

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [28]:
arr_6 = np.arange(100,step=2)#不包含stop值，默认start是0
arr_6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

### 随机生成ndarray
- numpy.random.random()
- numpy.random.randint()
- numpy.random.uniform()
- numpy.random.randn()
- numpy.random.nomal()

In [29]:
arr_7 = np.random.random((3,2))#取值范围[0,1)
arr_7

array([[0.91131385, 0.33918057],
       [0.04183866, 0.15059878],
       [0.3892588 , 0.18631539]])

In [30]:
arr_8 = np.random.randint(10,size=(5,3))
arr_8

array([[9, 7, 1],
       [3, 0, 1],
       [5, 9, 3],
       [2, 8, 3],
       [7, 5, 6]])

In [34]:
arr_9 = np.random.uniform(1.5,5.5,size=(4,5))
arr_9

array([[3.10319768, 1.71221911, 4.6046022 , 2.28945209, 5.3805344 ],
       [3.11304668, 2.46936741, 1.79768947, 4.67011712, 5.42650607],
       [2.9230885 , 2.24477536, 3.60099322, 4.07491413, 4.98561122],
       [5.21265228, 1.88892138, 3.93851917, 4.08119179, 2.6203186 ]])

In [33]:
# ndarray的元素是否可以四舍五入？
round(4.5555555,2)

4.56

In [5]:
arr_10 = np.random.randn(3,2,4)
arr_10

array([[[-0.52817175, -1.07296862,  0.86540763, -2.3015387 ],
        [ 1.74481176, -0.7612069 ,  0.3190391 , -0.24937038]],

       [[ 1.46210794, -2.06014071, -0.3224172 , -0.38405435],
        [ 1.13376944, -1.09989127, -0.17242821, -0.87785842]],

       [[ 0.04221375,  0.58281521, -1.10061918,  1.14472371],
        [ 0.90159072,  0.50249434,  0.90085595, -0.68372786]]])

In [3]:
np.random.seed(1) #随机种子：使用相同的种子，每次生成的数据是一样的
np.random.random((3,2))

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02]])

### ndarray 对象的属性
- ndim,维度，一个数值，如：2
- shape 形状，是一个元组，如(3,)或(3,2)
- size 元素的总大小，即元素的个数
- dtype 元素的数据类型 

In [6]:
arr_10.ndim

3

In [9]:
display(arr_10.shape)
display(arr_10.size)
display(arr_10.dtype)

(3, 2, 4)

24

dtype('float64')

### ndarray 的索引操作
- 索引位置
    - a[下标]
    - a[行下标，列下标]
    - a[[下标1，下标2, ...]]
    
- 索引切片
    - a[起始:结束:步长]
    - a[:结束]从0开始
    - a[:,下标]

In [12]:
# 生成5位同学的三门课程成绩表
d = np.random.randint(100,size=(5,3))
d

array([[23, 15, 87],
       [25, 71, 92],
       [74, 62, 46],
       [32, 88, 23],
       [55, 65, 77]])

In [13]:
#查看第3位同学的第2门课程的成绩
d[2,1]

62

In [15]:
#查看第2、4、5位同学的第1门和第3门课程的成绩
d[[1,3,4]][:,[0,2]]

array([[25, 92],
       [32, 23],
       [55, 77]])

In [17]:
d[:3,:2]

array([[23, 15],
       [25, 71],
       [74, 62]])

In [18]:
#将所有列反转一下
d[:,::-1]

array([[87, 15, 23],
       [92, 71, 25],
       [46, 62, 74],
       [23, 88, 32],
       [77, 65, 55]])

### 变形与转置
- ndarray.reshape()变形
- ndarray.T/transponse()矩形的转置

In [36]:
d = np.random.randint(100,size=24)
d

array([53, 47, 60, 34, 32, 19, 67, 24, 83, 94, 38, 47,  5, 79, 63, 87, 32,
       42, 74, 66, 88, 98, 30, 17])

In [37]:
d.reshape(-1)

array([53, 47, 60, 34, 32, 19, 67, 24, 83, 94, 38, 47,  5, 79, 63, 87, 32,
       42, 74, 66, 88, 98, 30, 17])

In [21]:
d.shape

(24,)

In [23]:
d.reshape((3,8))

array([[57, 82, 96, 13, 10, 23, 81,  7],
       [24, 74, 92, 20, 32, 12, 65, 94],
       [60, 24, 82, 97,  2, 92, 98, 10]])

In [24]:
#变成2列，任意行数
d.reshape((-1,2))

array([[57, 82],
       [96, 13],
       [10, 23],
       [81,  7],
       [24, 74],
       [92, 20],
       [32, 12],
       [65, 94],
       [60, 24],
       [82, 97],
       [ 2, 92],
       [98, 10]])

### 注意：无论如何变形，数组的总长度size不会变的。

In [26]:
d2 = d.reshape((3,8))
d2

array([[57, 82, 96, 13, 10, 23, 81,  7],
       [24, 74, 92, 20, 32, 12, 65, 94],
       [60, 24, 82, 97,  2, 92, 98, 10]])

In [27]:
d2.T

array([[57, 24, 60],
       [82, 74, 24],
       [96, 92, 82],
       [13, 20, 97],
       [10, 32,  2],
       [23, 12, 92],
       [81, 65, 98],
       [ 7, 94, 10]])

In [29]:
d2.transpose()

array([[57, 24, 60],
       [82, 74, 24],
       [96, 92, 82],
       [13, 20, 97],
       [10, 32,  2],
       [23, 12, 92],
       [81, 65, 98],
       [ 7, 94, 10]])

#扩展任务
1.给定一个数据库表A，内容如下：
    year,month,amount
    1991,1,    1.1
    1991,2,    1.2
    1992,1,    2.1
    1992,2,    2,2
请写出SQL语句，让查询的结果为：
    year，m1, m2
    1991,1.1, 1.2
    1992,2.1, 2,2
提示： 使用if()函数或自连表查询

### ndarray的级联
将多个数组按水平或垂直的方向进行拼接，axis表示级联的方向
- np.concatenate((a1,a2,...),axis=0)
- np.hstack((a1,a2,...))水平方向
- np.vstack((a1,a2,...))垂直方向

In [32]:
#生成两个三位学生的2门课程的成绩表，并且合成4门课程的3位同学的成绩表
s1 = np.random.randint(100,size=(3,2))
s2 = np.random.randint(100,size=(3,2))
np.concatenate((s1,s2),axis=1)

array([[42, 20, 53, 84],
       [48, 22, 10, 96],
       [13, 97, 55, 61]])

#ndarray 的切割
- np.split(arr,indexies_or_sections,axis=0)
- np.hsplit()
- np.vsplit()


In [33]:
s3 = np.random.randint(100,size=(10,6))
s3

array([[56, 89, 21, 96, 83, 25],
       [14, 13, 84, 43,  6, 77],
       [56, 59, 15, 24,  9, 66],
       [71, 53, 69, 36, 21, 40],
       [77, 91, 49, 47, 77, 40],
       [78, 45, 87, 16, 28, 45],
       [67, 66, 78, 46,  0, 29],
       [63, 75, 35, 53, 93, 33],
       [ 2, 84, 83, 48, 54, 32],
       [28, 55, 82, 31, 28, 94]])

In [34]:
np.split(s3,[3],axis=1)

[array([[56, 89, 21],
        [14, 13, 84],
        [56, 59, 15],
        [71, 53, 69],
        [77, 91, 49],
        [78, 45, 87],
        [67, 66, 78],
        [63, 75, 35],
        [ 2, 84, 83],
        [28, 55, 82]]), array([[96, 83, 25],
        [43,  6, 77],
        [24,  9, 66],
        [36, 21, 40],
        [47, 77, 40],
        [16, 28, 45],
        [46,  0, 29],
        [53, 93, 33],
        [48, 54, 32],
        [31, 28, 94]])]