In [1]:
import numpy as np

### 矩阵操作
- 广播机制(重要)
- 维度不足时，自动补1
- 用现有的值填充假定缺失的值
- 算术运算
- 矩阵积

In [3]:
a3 = np.random.randint(1,10,size=(3,4))
a3

array([[8, 3, 1, 3],
       [8, 7, 7, 5],
       [4, 9, 1, 8]])

In [4]:
a2 = np.random.randint(1,10,size=(2,3))
a2

array([[8, 5, 8],
       [2, 9, 2]])

In [7]:
np.dot(a2,a3)

array([[136, 131,  51, 113],
       [ 96,  87,  67,  67]])

### 排序操作
- np.argmin()/np.argmax()
- np.sort()/ndarray.sort()
- np.partotion(a.k)#部分排序


In [8]:
a4 = np.random.randint(1,100,size=20)
a4

array([47,  5, 54, 94, 33, 25, 10, 81, 80, 40, 57, 14, 45, 57, 17, 20, 36,
       65, 29, 23])

In [12]:
for i in range(a4.size-1):
    min_i = np.argmin(a4[i:])
    if a4[i] > a4[min_i + i] :
        a4[i],a4[min_i] = a4[min_i],a4[i]
print(a4)

[ 5 57 40 94 81 25 10 33 80 45 57 14 65 29 17 20 36 54 47 23]


In [ ]:
#任务1：比较其他的排序方式，查看每种排序的执行时间